import z, { number, object, string } from 'zod/v4';

export const DeviceConfig = object({
	UPDATE_URL: string().nonempty().optional(),
	END_ROUTE_FORGOTTEN: string().nonempty().optional(),
	REFRESH_ROUTE: string().nonempty().optional(),
	UPDATE_STATUS: string().nonempty().optional(),
	INFO_PRODUCT: string().nonempty().optional(),
	UPDATE_STATUS_IN: string().nonempty().optional(),
	LIVE_CAPTURE: string().nonempty().optional(),
	INFO_MODEL: string().nonempty().optional(),
	TRACK_CAPTURE: string().nonempty().optional(),
	SAVE_OFFLINE: string().nonempty().optional(),
	INFO_BRAND: string().nonempty().optional(),
	SERVER_API: string().nonempty().optional(),
	STOP_RATIO: string().nonempty().optional(),
	SESSION_MAX_TIME: string().nonempty().optional(),
	SERVICE_TICK: string().nonempty().optional(),
	PARAM_UPDATE: string().nonempty().optional(),
	TRACK_CAPTURE_OUT: string().nonempty().optional(),
	PHOTO_MIN: string().nonempty().optional(),
	INFO_SERIAL: string().nonempty().optional(),
	INFO_MANUFACTURER: string().nonempty().optional(),
	STOP_TIME: string().nonempty().optional(),
	INFO_FINGERPRINT: string().nonempty().optional(),
	INTERNET_TEST: string().nonempty().optional(),
	EMERGENCY_NUMBER: string().nonempty().optional(),
	SAVE_ONLINE: string().nonempty().optional(),
	AUTOSELECT: string().nonempty().optional(),
	PHOTO_MAX: string().nonempty().optional(),
	MAX_POINT_DIST: string().nonempty().optional(),
	VERSION: string().nonempty().optional(),
	SERVER_TRACK: string().nonempty().optional(),
	INFO_DEVICE: string().nonempty().optional(),
	IDENTIFIER: string().nonempty().optional(),
	IMEI: string().nonempty().optional(),
	LASTTIME: number().nonnegative().optional(),
});

export type DeviceConfig = z.infer<typeof DeviceConfig>;
