import z, { boolean, number, object, string } from 'zod/v4';

export const DeviceState = object({
	USSD_NUMBER: string().nonempty().optional(),
	LOST_TRACKS: string().nonempty().optional(),
	TRACK_END: string().nonempty().optional(),
	USSD_CREDIT_TOTAL: string().nonempty().optional(),
	ID_SESSION: string().nonempty().optional(),
	UPDATE_DOWNLOADED: string().nonempty().optional(),
	TRACK_INI: string().nonempty().optional(),
	NOTIF_TITLE: string().nonempty().optional(),
	USSD_SESSION_TIME: string().nonempty().optional(),
	ON_ROUTE: string().nonempty().optional(),
	LAST_UPDATE_DB: string().nonempty().optional(),
	IS_EMERGENCY: string().nonempty().optional(),
	ID_ROUTE: string().nonempty().optional(),
	IS_INTERNET: string().nonempty().optional(),
	IS_SESSION: string().nonempty().optional(),
	USSD_CREDIT_ADD: string().nonempty().optional(),
	EMERGENCY_NUMBER: string().nonempty().optional(),
	NOTIF_REQ: string().nonempty().optional(),
	NOTIF_DESC: string().nonempty().optional(),
	MESSAGE_RX: string().nonempty().optional(),
	IS_GPS: string().nonempty().optional(),
	SESSION_BAT: string().nonempty().optional(),
	LAST_TRACK_ID: string().nonempty().optional(),
	IS_SERVICE: string().nonempty().optional(),
	PAUSE_INI: string().nonempty().optional(),
	IS_LIVE: string().nonempty().optional(),
	REQ_LIVE: string().nonempty().optional(),
	ID_LOCATION: string().nonempty().optional(),
	USSD_SESSION_CREDIT_MAIN: string().nonempty().optional(),
	ID_SERVICE: string().nonempty().optional(),
	USSD_CREDIT_DATA: string().nonempty().optional(),
	COMPLETED: string().nonempty().optional(),
	ABANDONED: string().nonempty().optional(),
	USSD_CREDIT_DATE: string().nonempty().optional(),
	USSD_TIME: string().nonempty().optional(),
	STOP_COUNT: string().nonempty().optional(),
	USSD_SESSION_CREDIT_ADD: string().nonempty().optional(),
	USSD_CREDIT_MAIN: string().nonempty().optional(),
	USSD_SESSION_CREDIT_TOTAL: string().nonempty().optional(),
	SESSION_END: string().nonempty().optional(),
	PER_ACCESSIBILITY: string().nonempty().optional(),
	IS_TRACK: string().nonempty().optional(),
	LAST_VERSION: string().nonempty().optional(),
	ID_ASSIGNMENT: string().nonempty().optional(),
	USSD_SESSION_CREDIT_DATE: string().nonempty().optional(),
	SESSION_START: string().nonempty().optional(),
	MESSAGE_TX: string().nonempty().optional(),
	ID_USER: string().nonempty().optional(),
	IS_PAUSE: number().nonnegative().optional(),
	REQ_TRACK: string().nonempty().optional(),
	ACTIVITY: string().nonempty().optional(),
	USSD_SESSION_CREDIT_DATA: string().nonempty().optional(),
	EMERGENCY_ID: string().nonempty().optional(),
	EVENT: string().nonempty().optional(),
	SPEED: string().nonempty().optional(),
	IGNITION: boolean().default(false).optional(),
});

export type DeviceState = z.infer<typeof DeviceState>;
