name: Auto assign PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign PR
        uses: peter-evans/assign-issue@v2
        with:
          assignees: Maur025

      - name: Add reviewer
        uses: madrapps/add-reviewers@v1
        with:
          reviewers: Maur025
