name: Auto assign PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign PR
        uses: ahmadnassri/action-auto-assign@v2
        with:
          config: .github/auto_assign.yml
