name: Deploy Docusaurus site in GitHub Pages

on:
  push:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - '.github/workflows/docusaurius-deploy.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Docusaurus site
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build docusaurus site
        working-directory: './docs'
        run: pnpm build

      - name: upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/build'

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
